
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 21 18:03:25 BRST 2016
//----------------------------------------------------

package AnalizadorSintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 34;
  public static final int AC = 45;
  public static final int MULT = 15;
  public static final int VI = 51;
  public static final int REPEAT = 7;
  public static final int FX = 44;
  public static final int MAIORIGUAL = 23;
  public static final int ERRO = 3;
  public static final int FOR = 28;
  public static final int UNIAO = 19;
  public static final int DPH = 18;
  public static final int AND = 37;
  public static final int NOT = 27;
  public static final int MENORIGUAL = 21;
  public static final int IGUAL = 47;
  public static final int FP = 42;
  public static final int ELSEIF = 11;
  public static final int NIL = 29;
  public static final int OR = 38;
  public static final int IN = 32;
  public static final int DIV = 16;
  public static final int UNTIL = 8;
  public static final int IF = 9;
  public static final int FC = 46;
  public static final int EOF = 0;
  public static final int RETURN = 35;
  public static final int MAIOR = 22;
  public static final int TRUE = 31;
  public static final int error = 1;
  public static final int PERCENT = 17;
  public static final int MENOR = 20;
  public static final int NUMBER = 39;
  public static final int BREAK = 36;
  public static final int TRALHA = 26;
  public static final int TRESPT = 48;
  public static final int NAME = 40;
  public static final int ELSE = 12;
  public static final int MEN = 14;
  public static final int IGUALIGUAL = 24;
  public static final int WHILE = 6;
  public static final int THEN = 10;
  public static final int END = 5;
  public static final int SUM = 13;
  public static final int AX = 43;
  public static final int STRING = 2;
  public static final int LOCAL = 33;
  public static final int FALSE = 30;
  public static final int APROXIGUAL = 25;
  public static final int AP = 41;
  public static final int DP = 52;
  public static final int DO = 4;
  public static final int PV = 50;
  public static final int UMPT = 49;
}

