/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import AnalizadorLexico.*;
import AnalizadorSintatico.parser;

import Auxiliares.Auxiliar;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.io.StreamTokenizer;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTree;

/**
 *
 * @author Daniel Ogg
 */
public class Codigo extends javax.swing.JFrame {

    /**
     * Creates new form Codigo
     */
    public Codigo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        codeArea = new javax.swing.JTextArea();
        verTokensBt = new javax.swing.JButton();
        analiseCompletaBt = new javax.swing.JButton();
        novoDocumentoBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codeArea.setColumns(20);
        codeArea.setRows(5);
        jScrollPane1.setViewportView(codeArea);

        verTokensBt.setText("Ver Tokens");
        verTokensBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTokensBtActionPerformed(evt);
            }
        });

        analiseCompletaBt.setText("Realizar Análise Completa");
        analiseCompletaBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analiseCompletaBtActionPerformed(evt);
            }
        });

        novoDocumentoBt.setText("Novo Documento");
        novoDocumentoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoDocumentoBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(analiseCompletaBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(verTokensBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(novoDocumentoBt)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(verTokensBt)
                        .addGap(18, 18, 18)
                        .addComponent(analiseCompletaBt)
                        .addGap(18, 18, 18)
                        .addComponent(novoDocumentoBt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void verTokensBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTokensBtActionPerformed
        FileWriter raf = null;
        
        try {
            raf = new FileWriter("ficheiro.txt");
            raf.write(codeArea.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Codigo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Codigo.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try {
                raf.close();
                 ListarTokens novo = new ListarTokens();
                              
                              novo.setVisible(true);
                             
                             
            } catch (IOException ex) {
                Logger.getLogger(Codigo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_verTokensBtActionPerformed

    private void analiseCompletaBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analiseCompletaBtActionPerformed
        // TODO add your handling code here:
       FileWriter raf = null;
       FileWriter saida = null;
        try {
            saida=new FileWriter("auxiliar.txt");
            saida.close();
            raf = new FileWriter("ficheiro.txt");
            raf.write(codeArea.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Codigo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Codigo.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try {
                
                raf.close();
                
                 ScannerJLexer scan = new ScannerJLexer(new FileReader("ficheiro.txt"));
                     parser  p = new parser(scan);
                      Object result = p.parse().value;
                       JOptionPane.showMessageDialog(null, p.resultado);
                       Auxiliar au =  new Auxiliar();
                                au.inverteArq();
                     
            } catch (IOException ex) {
                Logger.getLogger(Codigo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
               Logger.getLogger(Codigo.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_analiseCompletaBtActionPerformed

    private void novoDocumentoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoDocumentoBtActionPerformed
        // TODO add your handling code here:
       
        FileWriter saida = null;
     
        try {
            saida=new FileWriter("auxiliar.txt");
            saida.close();
        } catch (IOException ex) {
            Logger.getLogger(Codigo.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
          codeArea.setText("");
    }//GEN-LAST:event_novoDocumentoBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Codigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Codigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Codigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Codigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        //</editor-fold>
        //String caminho = "C:/Users/Leandro/Desktop/Leandro/Faculdade/COMP/TrabalhoCompiladoresV3/src/AnalizadorLexico/Lexema.flex";;
        //File arq = new File(caminho);
        //jflex.Main.generate(arq);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Codigo().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analiseCompletaBt;
    private javax.swing.JTextArea codeArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novoDocumentoBt;
    private javax.swing.JButton verTokensBt;
    // End of variables declaration//GEN-END:variables
}
